### ISSUE TITLE
Ønsker vi å sette opp kanal på Gitter.im?

### ISSUE THREAD

**Issue by Starefossen** [iojs/iojs-no#13]
Er det ønskelig å sette opp egen kanal for iojs-no på Gitter.im? Ser at mange av de andre lokale iojs-gruppne allerede har satt opp slike kanaler.  Det finnes forøvrig to tråder på som diskuterer tilsvarende tema på iojs/website#107 og iojs/website#106.

**Comment by asbjornenge** [comment]
:+1: fra meg :smile:

**Comment by ekmartin** [comment]
Kan vel eventuelt også bruke #io.js-no på Freenode, men det er kanskje enklere med en Gitter-kanal?

**Comment by asbjornenge** [comment]
@Starefossen har allerede satt opp et rom her https://gitter.im/iojs/iojs-no fikler til ei lenke på README før jeg closer

**Comment by Starefossen** [comment]
@asbjornenge du kan merge [denne](https://github.com/iojs/iojs-no/pull/20) og lukke begge kanskje?
