### ISSUE TITLE
Bedre menylinje?

### ISSUE THREAD

**Issue by eiriksm** [iojs/iojs-no#22]
Hei!

To ting egentlig:
- Menylinjen burde være konsekvent på casing generelt. Om "blogg" skal stå i uppercase, så er det ingen grunn til at "API-dokumentasjon" ikke skal det. Personlig heller jeg mer mot at blogg har vanlig casing.
- Det er for lite plass til alle menypunktene på mobil. 

Jeg fikser mer enn gjerne dette, men et par spørsmål først (i tillegg til det med casing, selvsagt):

For å få plass til alle linkene på mobil må vi gjøre en eller flere av følgende:
- Ha noen form for kollapsing av meny (off canvas eller drop down?)
- Kutte ned på fontstørrelse / padding
- Endre ordlyd (f.eks er jo punktet API-dokumentasjon ganske stort)

Dette er jo riktignok mine meninger, så om folk generelt synes det ser greit ut så er det cool :)

![screen shot 2015-02-09 at 12 05 22](https://cloud.githubusercontent.com/assets/865153/6105123/20b111e6-b054-11e4-9303-dff59bccd29e.png)

**Comment by mikaelbr** [comment]
Hei!

«BLOGG» var noe jeg la til kjapt i går for at bloggen skulle være tilgjengelig et sted. Kanskje det til og med heller burde være i footer av siden fremfor i headeren.

Jeg tror API-dokumentasjon gjerne egentlig kun kan være «API» (tror API-dokumentasjon er noe redundant). Og dersom alle meny-punkter er akronymer og uppercase, ser det kanskje estetisk best ut med uppercase BLOGG også?

Med API-lenke som kun «API» vil det være plass på mobil, men man kan fremdeles vurdere å ha Blogg i footer.

**Comment by Starefossen** [comment]
Se iojs/iojs-no#17 og iojs/website#136

>  Internal structure on the site is about to change wildly though, so be aware.

**Comment by eiriksm** [comment]
Ah. Da er det kanskje ikke noe å bruke for mye energi på. 

Jeg liker forslaget om å bare korte ned til "API". Enkel løsning, som ikke har så mye å si om strukturen "endres vilt".

**Comment by Starefossen** [comment]
Enig! Den bryter også veldig med de andre meny-elementene slik den er nå.
