### ISSUE TITLE
Oversette "io.js Week of February 6th 2015" 

### ISSUE THREAD

**Issue by mikaelbr** [iojs/iojs-no#3]
Oversett ukentlige nyhetsbrev fra https://medium.com/@iojs .

Denne issuen gjelder første innlegget: [io.js Week of February 6th 2015](https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4)

Etter oversettelse kan det publiseres på enten medium eller et egen blogg-verktøy på http://iojs.no?

**Comment by Starefossen** [comment]
Hvis noen vil ta ansvar for å lage en norsk konto på medium så er det bare å kjøre på. Ellers ser jeg for meg at vi setter opp Github pages / Jekyll på dette repoet slik at vi enkelt kan publisere norske docs og poster til iojs.no.

**Comment by mikaelbr** [comment]
Det tror jeg nok er en god plan. Men i mellomtiden, inntil noe slik er opprettet, kan noe som Medium brukes?

**Comment by Starefossen** [comment]
Absolutt! Vil du opprette en konto på Medium og poste en oversettelse av den siste posten?

**Comment by mikaelbr** [comment]
Ja, kan gjøre det tidlig i morgen!

**Comment by Andersos** [comment]
+1 for Jekyll

**Comment by Andersos** [comment]
Er det noen som har startet på denne?

**Comment by mikaelbr** [comment]
Ja, har halve oversettelsen liggende. Kommer straks

**Comment by mikaelbr** [comment]
Her er foreløpig oversettelse. Dersom det skal være en konto på Medium må det sikkert være en e-post å registrere det på, og da samme som twitter-kontoen? Kanskje like greit å ha det som markdown-filer i repoet?

---

# io.js Uken 6. februar 2015

Atom og nw.js nå med io.js, Linux Tracing og mye mer.

Hver fredag vil det komme et ukentlig nyhetsbrev som vil vise hendelser og nyheter både i og i rundt io.js.

Vi gikk igjennom alle bidrag i januar og fant at dette var den 3. mest aktive måneden i hele Node.js' historie (med 294 commits) og den mest aktive måneden på nesten 3 år (308 commits i februar 2012). Følgende denne trenden med bidrag, forventer vi å at februar vil være enda mer aktiv.
- [1.1.0](https://iojs.org/dist/v1.1.0/) ble lansert, mer informasjon i [endringsloggen](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#2015-02-03-version-110-chrisdickinson).
- [Enklere opprettelse av streams](https://github.com/iojs/io.js/commit/50daee7243a3f987e1a28d93c43f913471d6885a) implementert av Sam Newman.
- Linux Tracing (LTTNG) [kommer](https://github.com/iojs/io.js/pull/702)
- Google skriver litt om [deres arbeid rundt Tracing i V8 og Chrome](https://github.com/iojs/io.js/issues/671#issuecomment-73191538), etter at samarbeidet rundt feilsøking i io.js utvides.
- [Travisci støtter nå io.js](http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/)
- [Codeship støtter også io.js](https://codeship.com/documentation/languages/nodejs/#iojs)
- [Editoren Atom er nå flyttet over til io.js](https://github.com/atom/atom/releases/tag/v0.177.0)
- nw.js (tidligere node-webkit) går [over til io.js](https://github.com/nwjs/nw.js/issues/2742)
- Nye Tessel-maskinvarer [kommer til å støtte io.js](http://blog.technical.io/post/110115579867/upcoming-hardware-from-technical-machine)
- Chris Dickinson hentet inn [6 nye bidragsytere](https://github.com/iojs/io.js/issues/680#issuecomment-73089691), og øker antallet totale **bidragsytere til 23**.
- Arbeid pågår om en ny [stabilitet- og kompabilitetsstrategi](https://github.com/iojs/io.js/issues/725) og oppfordrer til bidrag fra fellesskapet.
- Vi har kontaktet [forskjellige bedrifter for tilbakemelding](https://github.com/iojs/roadmap/issues/13) på fremdriftsplanen vår. Si gjerne i fra dersom du har konfaktinformasjonen til noen bedrifter vi burde kontakte.
- Neste uke starter [Node Summit](http://nodesummit.com/) med mange io.js foredragsholdere og deltakere.
- [Ukentlig TC-møte (teknisk komité)](https://www.youtube.com/watch?v=IhXa2FmtBI4).
- [Arbeidsgruppe-møte for nettsiden](https://www.youtube.com/watch?v=SBJaXUA0lSY).
- [Arbeidsgruppe-møte for Tracing](https://www.youtube.com/watch?v=Oar2yB5SPtA).

**Comment by mollerse** [comment]
Hvis du legger den til i repoet så kan vi få inn bidrag på skrivleifer og lignende

**Comment by mikaelbr** [comment]
Jepp. Det var tanken min og og hovedårsaken til at jeg la det ut her nå. Uansett greit å ha det organisert i en mapper på github.

**Comment by Starefossen** [comment]
Jeg holder på med en Jekyll versjon av nettsiden som ligger i gh-branchen. Burde ikke ta lang tid å få den på plass. Vi trenger noe ny styling til de oversatte postene men ellers er jo alt likt.

**Comment by asbjornenge** [comment]
Godt jobba folkens :+1: @Starefossen gir du oss et vink når vi kan sjekke ut gh-pages? hvis @mikaelbr legger oversettelsen som en md fil der så fant jeg et par små skirveleifs. Ellers veldig bra :grin:

**Comment by mikaelbr** [comment]
@Starefossen Så du hadde Jekyll oppe og jeg var i gang med å legge ut, men ser at du har gjort det :+1: Men da er vel egentlig ikke jeg assigna på denne lengre?

**Comment by Starefossen** [comment]
Har pushet oversettelsen til @mikaelbr, den ligger nå [her](https://github.com/iojs/iojs-no/blob/gh-pages/_posts/2015-02-06-februar.md). Har også pushet alle mine Jekyll endringer til gh-pages og har satt den til primær branch for repoet. Alle endringer blir nå live på [iojs.no](http://www.iojs.no) når dere pusher endringer.

**Comment by Starefossen** [comment]
@mikaelbr beklager dårlig kommunikasjon fra min side. Mente å assigne deg for selve oversettings-jobben. Godt jobba! Skal vi kan lukke denne issuen nå siden oversettingen er ferdig, og så kan de som har endringer fikse de direkte eller opprette nye issues?

**Comment by mikaelbr** [comment]
Høres bra ut. Gitt at noen går over og kvalitetssikrer oversettelsen.

**Comment by Starefossen** [comment]
Tenker at vi bør utarbeide noen enkle retningslinjer for større endringer som nye poster osv. at de blir lagt ut som pull requests slik at vi kan diskutere og kommentere endringene før de merges inn i gh-pages.

**Comment by mikaelbr** [comment]
Ja, burde ha en viss flyt / rutine for innlegg så det kan kvalitetssikres på en måte.
