### ISSUE TITLE
WebRebels 2015

### ISSUE THREAD

**Issue by Andersos** [iojs/iojs-no#30]
WebRebels er en relevant konferanse for de som er interesert i io.js.
Første billettslipp start på fredag 13. feb kl 13:00. 
For mer informasjon sjekk ut nettsiden [webrebels.org](https://www.webrebels.org/).

**Comment by asbjornenge** [comment]
Var der i fjor og skal i år :grin: Kan virkelig anbefale WebRebels til alle som driver med web og js :rocket: Reach out hvis noen av dere skal da, så kan vi møtes :+1:

**Comment by zrrrzzt** [comment]
Forsøkte å få billetter ifjor, men uten hell. Sitter klar på fredag for et nytt forsøk.

**Comment by asbjornenge** [comment]
Jeg også :stuck_out_tongue_closed_eyes:

**Comment by zrrrzzt** [comment]
De forsvant kjapt gitt... no luck for me

**Comment by mollerse** [comment]
Kommer 2 batches til, så det er fortsatt muligheter
