### ISSUE TITLE
Tittel for ukentlig oppdatering

### ISSUE THREAD

**Issue by tmn** [iojs/iojs-no#33]
Vi har vært innom
- io.js Uken &lt;dato&gt;. &lt;mnd&gt; &lt;år&gt; - _io.js Uken 13. februar 2015_
- io.js oppdatering uke &lt;ukenr&gt;, &lt;mnd&gt; &lt;år&gt; - _io.js oppdatering uke 7, februar 2015_

Den første benyttes på `/blogg.html`, og den andre benyttes som tittel i selve posten. Foreslår at vi går for samme tittel i oversikten som i selve posten. Skal vi også vurdere å droppe måneden om vi går for ukenummer?
- io.js oppdatering uke 7. 2015
- io.js oppdatering uke 7, 2015
- io.js oppdatering uke 7 - 2015
- io.js oppdatering uke 7/2015

(kanskje droppe _io.js_ også?).

Eller noe slikt, om dato er morsommere enn ukenummer
- Ukens oppdatering. 7. februar 2015

**Comment by zrrrzzt** [comment]
Jeg gir min stemme til "Ukens oppdatering <dato>", alternativt "io.js oppdatering <dato>"

**Comment by mollerse** [comment]
Ukens oppdatering, <dato> - _Ukens oppdatering, 13. februar 2015_

Du vet jo allerede at du er inne på en iojs-side, så det trengs strengt tatt ikke å repeteres i tittelen tenker jeg. Er ikke så veldig stor fan av ukenummere, de er litt ullne, foretrekker å bruke datoer.

**Comment by Starefossen** [comment]
Stemmer også for _Ukens oppdatering, 13. februar 2015_

**Comment by mikaelbr** [comment]
Ja, ukenummer sier meg absolutt ingenting. «iojs» er totalt redundant. _Ukens oppdatering, 13. februar 2015_ ser absolutt best ut.
