### ISSUE TITLE
Oppdatert FAQ på website repoet

### ISSUE THREAD

**Issue by eiriksm** [iojs/iojs-no#45]
Hei!

På nodejs/website#357 er det merget at FAQ seksjonen skal omformuleres bittelitt. Jeg oppdaterte den norske oversettelsen av dette på nodejs/website#377, men den trenger vel en +1 fra noen andre i det norske teamet.

Jepp, det var bare det. God helg :)

**Comment by Andersos** [comment]
Denne kan vel lukkes nå?

**Comment by mikaelbr** [comment]
Jepp!
