### ISSUE TITLE
Proposal: rename the nodejs/iojs-no WG to nodejs/nodejs-no

### ISSUE THREAD

**Issue by srl295** [iojs/iojs-no#46]
Dear members of the io.js Norwegian WG `iojs-no`

It is proposed to rename this repo to:

   [nodejs/nodejs-no](https://github.com/nodejs/nodejs-no/)

As part of the io.js and node.js convergence, node.js releases are now based on the codebase and user base of the converged node.js and io.js communities. A number of the resources and repositories have already been renamed.
In the absence of objections or other discussion, this rename will occur on or after [Oct 28, 2015](http://time.is/1200AM_28_Oct_2015_in_GMT?iojs-rename)

However, active language working groups should take ownership of this issue and discuss/dispose of it according to their own processes.

For more information or to discuss the overall issue, please see and comment on https://github.com/nodejs/node/issues/2525

This statement was authorized by the Node.js TSC

Cc: @nodejs/iojs-no

**Comment by mikaelbr** [comment]
Seems reasonable to me. I don't see any reason why we couldn't just rename the repo now.
Also, we have to "deprecate" the `http://iojs.no` domain and instead redirect to the node.js pages.

**Comment by Starefossen** [comment]
Yeah, I think we should go ahead with the rename. Regarding the iojs.no domain it redirects to iojs.org which I think is the most correct thing to do.

**Comment by mikaelbr** [comment]
Yeah, you're right. It's probably the best thing to do. In addition to changing the repo name we have to do internationalisation of the nodejs page and get nodejs.no to point to that translation.

**Comment by Andersos** [comment]
I'm also in favor of the renaming.

**Comment by asbjornenge** [comment]
:+1: :rocket:

**Comment by mollerse** [comment]
:+1:

**Comment by eiriksm** [comment]
:+1:

**Comment by mikaelbr** [comment]
After no objections, I just went ahead and renamed the repo. It's now https://github.com/nodejs/nodejs-no. `iojs-no` is redirected to `nodejs-no`, so hopefully this didn't break anything.
