### ISSUE TITLE
Hvem vil ha en @iojs.no epost-adresse?

### ISSUE THREAD

**Issue by Starefossen** [iojs/iojs-no#8]
Er det noe interesse for `@iojs.no` epost-adresser? I så fall så kan jeg sette det opp og gi en adresse til alle som vil ha det.

**Comment by Andersos** [comment]
Kanskje du kan sette opp anders@iojs.no -> iojs@andersos.net

Hva med å lage en mailingliste som slutter på @iojs.no?

**Comment by Starefossen** [comment]
~~Det hadde absolutt vært en fordel å lage en fells-epost, eller epostliste, som sendte videre til alle oss her i io.js Norge.~~

**Comment by leftieFriele** [comment]
om vi kjører all komunikasjon via GH issues kan de som vil ha epost ha notifications?

**Comment by Starefossen** [comment]
Etter omtanke så heller jeg mot at vi ikke lager noe felles epost eller epost-liste men heller har all dialog her på GitHub hvor alle enkelt kan abonnere på varsler og søke gjennom diskusjonene.

De som ønsker en privat @iojs.no adresse for å representere prosjektet kan få det.

**Comment by mikaelbr** [comment]
Tror det lureste er å holde kommunikasjonen minst mulig fragmentert. Det blir mye administrativt overhead for kommunikasjon dersom man må ha mail, github, twitter, ++.

**Comment by zrrrzzt** [comment]
Så langt det er mulig går min stemme til å holde alt her inne på GitHub.
